from datetime import datetime
from database import db
from community_service import scoped_query
from models import (
    Complaint, Application, Bolo, OfficerSession, Alert,
    RadioLog, ServerStatus, Inmate, Hearing,
    Civilian, Vehicle, License, Warrant, Arrest,
    Incident, Evidence, TrafficStop, Call911, ActivityLog,
)


# ---------------------------------------------------------------------------
# Serialisers (same field names as the original JSON shape)
# ---------------------------------------------------------------------------

def complaint_to_dict(c):
    return {
        'id': c.complaint_id,
        'complaintDiscord': c.complaint_discord,
        'reportedName': c.reported_name,
        'complaintType': c.complaint_type,
        'incidentDate': c.incident_date,
        'incidentLocation': c.incident_location,
        'witnesses': c.witnesses,
        'evidenceLink': c.evidence_link,
        'description': c.description,
        'resolution': c.resolution,
        'status': c.status,
        'staffNotes': c.staff_notes or '',
        'submittedAt': c.submitted_at.isoformat() if c.submitted_at else None,
        'updatedAt': c.updated_at.isoformat() if c.updated_at else None,
    }


def application_to_dict(a):
    return {
        'id': a.application_id,
        'appDiscord': a.app_discord,
        'appCharacter': a.app_character,
        'applicationType': a.application_type,
        'ageConfirmation': a.age_confirmation,
        'experience': a.experience,
        'roleReason': a.role_reason,
        'availability': a.availability,
        'status': a.status,
        'staffNotes': a.staff_notes or '',
        'submittedAt': a.submitted_at.isoformat() if a.submitted_at else None,
        'updatedAt': a.updated_at.isoformat() if a.updated_at else None,
    }


def bolo_to_dict(b):
    return {
        'id': b.bolo_id,
        'suspectName': b.suspect_name,
        'description': b.description,
        'lastLocation': b.last_location,
        'vehicle': b.vehicle or '',
        'charges': b.charges or '',
        'threatLevel': b.threat_level,
        'issuedBy': b.issued_by,
        'issuedAt': b.created_at.isoformat() if b.created_at else None,
        'status': b.status,
        'autoGenerated': b.auto_generated or False,
    }


def session_to_dict(s):
    return {
        'callsign': s.callsign,
        'name': s.officer_name or '',
        'department': s.department or 'LSPD',
        'loggedInAt': s.logged_in_at.isoformat() if s.logged_in_at else None,
        'status': s.status or 'On Duty',
    }


def alert_to_dict(a):
    return {
        'id': a.alert_id,
        'type': a.alert_type,
        'message': a.message,
        'issuedBy': a.issued_by,
        'issuedAt': a.created_at.isoformat() if a.created_at else None,
    }


def radio_to_dict(r):
    return {
        'id': r.log_id,
        'unit': r.unit,
        'channel': r.channel,
        'message': r.message,
        'timestamp': r.created_at.isoformat() if r.created_at else None,
    }


def status_to_dict(s):
    return {
        'cityStatus': s.city_status,
        'playerCount': s.player_count,
        'maxPlayers': s.max_players,
        'customMessage': s.custom_message,
        'lastUpdated': s.last_updated.isoformat() if s.last_updated else None,
    }


def inmate_to_dict(i):
    return {
        'id': i.inmate_id,
        'suspectName': i.suspect_name,
        'charges': i.charges or '',
        'penalty': i.penalty or '',
        'cell': i.cell or '',
        'bookedBy': i.booked_by,
        'arrestId': i.arrest_id or '',
        'estimatedRelease': i.estimated_release or '',
        'notes': i.notes or '',
        'status': i.status,
        'bookedAt': (i.booked_at.isoformat() + 'Z') if i.booked_at else None,
        'releasedAt': (i.released_at.isoformat() + 'Z') if i.released_at else None,
        'releasedBy': i.released_by or '',
        'releaseReason': i.release_reason or '',
        'updatedAt': (i.updated_at.isoformat() + 'Z') if i.updated_at else None,
    }


def hearing_to_dict(h):
    return {
        'id': h.hearing_id,
        'suspectName': h.suspect_name,
        'charges': h.charges or '',
        'hearingType': h.hearing_type,
        'scheduledAt': h.scheduled_at or '',
        'judge': h.judge or '',
        'notes': h.notes or '',
        'arrestId': h.arrest_id or '',
        'filingOfficer': h.filing_officer or '',
        'outcome': h.outcome or '',
        'status': h.status,
        'createdAt': (h.created_at.isoformat() + 'Z') if h.created_at else None,
        'updatedAt': (h.updated_at.isoformat() + 'Z') if h.updated_at else None,
    }


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------

def get_all_complaints():
    return [complaint_to_dict(c) for c in
            scoped_query(Complaint).order_by(Complaint.submitted_at.desc()).all()]


def get_all_applications():
    return [application_to_dict(a) for a in
            scoped_query(Application).order_by(Application.submitted_at.desc()).all()]


def get_all_bolos():
    return [bolo_to_dict(b) for b in
            scoped_query(Bolo).order_by(Bolo.created_at.desc()).all()]


def get_all_officer_sessions():
    sessions = scoped_query(OfficerSession).all()
    return {s.callsign: session_to_dict(s) for s in sessions}


def get_recent_alerts(limit=100):
    return [alert_to_dict(a) for a in
            scoped_query(Alert).order_by(Alert.created_at.desc()).limit(limit).all()]


def get_recent_radio_log(limit=100):
    entries = scoped_query(RadioLog).order_by(RadioLog.created_at.desc()).limit(limit).all()
    return [radio_to_dict(r) for r in reversed(entries)]


def get_server_status():
    status = ServerStatus.query.first()
    if status is None:
        status = ServerStatus(
            city_status='ACTIVE',
            player_count=0,
            max_players=32,
            custom_message='24/7 dispatch channel live',
        )
        try:
            db.session.add(status)
            db.session.commit()
        except Exception:
            db.session.rollback()
    return status_to_dict(status)


def get_all_inmates():
    return [inmate_to_dict(i) for i in
            scoped_query(Inmate).order_by(Inmate.booked_at.desc()).all()]


def get_all_hearings():
    return [hearing_to_dict(h) for h in
            scoped_query(Hearing).order_by(Hearing.scheduled_at.desc()).all()]
